customhost = "database-1.cvoosl9bnaez.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chanhongyu-employee"
customregion = "us-east-1"
